name: "Ruby on Rails CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  TEST:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          
          #name: staging_environment
          #url: https://github.com/Vishalwayal123/thoughtwin-dockerize.git
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        #uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.0'
          run: bundle install
  
          
      - name: Install dependencies
        run: bundle install   
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
         
      #- name: Set up database schema
      #  run: bin/rails db:create
      #- name: Set up database schema
      #  run: bin/rails db:migrate
        #run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake 
      - name: Run tests
        run: bundle exec rake
      
      
      


  
